# -*- coding: utf-8 -*-
"""Demo2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r9i5wMuk7LE7t9x-OzBALjUS6FdAQxGj
"""

def main():
    # Ask for user's year level
    year_level = input("What is your year level? ")

    # Ask for user's course
    course = input("What course are you studying? ")

    # Ask for user's university
    university = input("Which university are you attending? ")

    # Print the collected information
    print("\nThank you for providing your details!")
    print(f"Year Level: {year_level}")
    print(f"Course: {course}")
    print(f"University: {university}")

if __name__ == "__main__":
    main()