# -*- coding: utf-8 -*-
"""Demo1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r9i5wMuk7LE7t9x-OzBALjUS6FdAQxGj
"""

def main():
    # Ask for user's name
    name = input("What is your name? ")

    # Ask for user's age
    age = input("How old are you? ")

    # Ask for user's city
    city = input("Which city do you live in? ")

    # Print the collected information
    print("\nThank you for providing your details!")
    print(f"Name: {name}")
    print(f"Age: {age}")
    print(f"City: {city}")

if __name__ == "__main__":
    main()